### ISSUE TITLE
Native Jupyter Shortcuts Inactivated

### ISSUE THREAD

**Issue by cyniphile** [lambdalisue/jupyter-vim-binding#36]
In new jupyter notebooks all native jupyter shortcuts are disabled except `j` and `k` when in jupyter command mode (not jupyter-vim command mode). In legacy notebooks that I created with ipython notebook, none of the jupyter shortcuts work, even though the jupyter-vim shortcuts work fine.

These problems arise only after I run

```
%%javascript
Jupyter.utils.load_extensions('vim_binding/vim_binding')
```

**Comment by lambdalisue** [comment]
> all native jupyter shortcuts are disabled

That what this plugin stands for. This plugin provide Vim-like shortcuts.

**Comment by cyniphile** [comment]
Ivanov's Vimception keeps both sets of shortcuts which makes it very easy to move between cells and copy/paste/add/delete cells using native jupyter shortcuts and also edit within-cell using vim-like shortcuts. 

Currently with my installation of jupyter-vim-bindings, it's not possible to move between cells in old notebooks or copy/paste/add/delete new cells using shortcuts.

**Comment by lambdalisue** [comment]
> Ivanov's Vimception keeps both sets of shortcuts which makes it very easy to move between cells and copy/paste/add/delete cells using native jupyter shortcuts and also edit within-cell using vim-like shortcuts. 

While Jupyter provide non Vim flavour key binding.
I would like to disable most of default one.
For example, [in Jupyter](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/keyboardmanager.js)
- `O` is used for `toggle-cell-output-scrolled` but I feel `O` to put a line (cell) above
- `y` is used for `change-cell-to-code` but I feel `y` to yank (copy) a selection (cell)

That's why I said "That what this plugin stands for."

> Currently with my installation of jupyter-vim-bindings, it's not possible to move between cells in old notebooks or copy/paste/add/delete new cells using shortcuts.

What did you mean with "old notebooks"? jupyter-vim-binding is just a javascript plugin so it won't change any data structure or so on.
And jupyter-vim-binding provides different mappings. Use
- `yy` to copy (yank)
- `p` to paste
- `o` or `O` to insert a cell
- `dd` to delete

See mapping help (`help > Keyboard shortcut`) or https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L264-L335
