### ISSUE TITLE
Documentation or cheat-sheet?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lambdalisue/jupyter-vim-binding#47]
So, I'm new to Jupyter, but I'm an old vimmer; I'm a _little_ lost trying to figure out how to navigate a Notebook using Jupyter-Vim (mostly, `j` and `k` seem to work very unintuitively for me … but it looks like #27 is going to address that).

Especially for non-vim-initiates, it might be nice to have a summary of the mappings added / changed by this plugin, in the README? (=

**Comment by wilzbach** [comment]
Just go in the menu and search for the entry key bindings or press `H` or directly look into the source code. It's just one file and pretty straightforward ;-)
Might be nice to state this somewhere in the main parts of the documentation...

**Comment by lambdalisue** [comment]
The problem is that I'm not native English speaker and writing English document is tough job for me. So I would like to ask someone to add that kind of document ;-)

**Comment by giulioungaretti** [comment]
@lambdalisue  I am willing  to work on a documentation thingy. But don't we have it already defined in the .help part of the js file ?

**Comment by lambdalisue** [comment]
I'm not really sure about this issue while we have `H` mapping (or `<F1>` in next release) to show keyboard shortcuts for Jupyter as you said.
Additionally, I'm the author so I don't really know which part is difficult for beginner and should be documented...

This issue is not closed because I got no response from @ELLIOTTCABLE yet. So I'm just waiting for him to reply what he think (if `H` is enough for him requirements or not).

But writing tips on [Wiki](https://github.com/lambdalisue/jupyter-vim-binding/wiki) or correct my English or so on are always welcome ;-)

**Comment by ELLIOTTCABLE** [comment]
I didn't even realize H1 existed!

Maybe simply copy-paste the content into the README?

**Comment by lambdalisue** [comment]
> Maybe simply copy-paste the content into the README?

Do you really think it help? I feel it is a bit redundant while you can easily see same thing within Jupyter.

**Comment by lambdalisue** [comment]
@ELLIOTTCABLE Now jupyter-vim-binding has completely new README. Do you still think it should have more information?

**Comment by ELLIOTTCABLE** [comment]
This looks good! The documentation needs a general clean-up for various minor English issues, and if I have time, I'll happily contribute that. (Opening a new Issue for that, though; see #54.)

Also, see #55, re: copy-paste.
