### ISSUE TITLE
Escape doesn't bring back Jupyter mode

### ISSUE THREAD

**Issue by rforgione** [lambdalisue/jupyter-vim-binding#53]
### Summary

Previously (last week) when I was in cell-edit/vim-edit mode, a single escape would bring me into vim command mode, and a second escape would bring me into Jupyter mode. Upon re-installing today, the escape key is no longer working to bring me back into Jupyter mode. This makes it quite difficult to navigate around the notebook. 
### Environment
- [ ] Operating system : Ubuntu 14.04
- [ ] Web browser : Chrome 48.0.2564.116
- [ ] Version or revision of Jupyter Notebook : 4.1.0
- [ ] Revision of jupyter-vim-binding : c1dd836154041ab8684008f426a13afedd335b4e
### Behavior

Escape key does not bring up Jupyter mode.
#### Expected

Escape key brings up Jupyter mode.
#### Actual

Escape key does nothing when in vim command mode. 
### Step by step procedure
1. Open notebook file
2. Press "i" to enter vim mode
3. Press "Esc" to go back to Jupyter mode
### What you have done to solve the issue

Unsure how to proceed.

**Comment by traeki** [comment]
Hi, @rforgione.  I'm mostly just lurking on this repository, but I can tell you there's been a major and deliberate shift in how the extension functions, with a goal of being less "jupyter-like" and more "vim-like".

All functionality should still be present, but keybindings have moved around a lot.  In particular, the keybinding you are looking for (escape from "command-mode" to "jupyter-mode") is now Shift-Esc.

If you want the old behavior, your best bet is probably to roll back your client to a previous revision.  That said, you should poke around a bit at the new keybindings and experiment.  I think it's overall a much nicer and more intuitive layout.  And I think if you really wanted to change just that one thing you could mess with the .js files directly.  Some of the other modified bindings collided with OS X bindings I use daily, so I had to do that myself.

Again, I'm not a contributor, so take this with a salt lick.  But I hope it helps, in the meantime.

-John

**Comment by rforgione** [comment]
Hi John,

Thanks so much for taking the time to read and respond! That makes a lot of sense. I'll have to give the new approach a fair shot before changing anything. 

-Rob

**Comment by lambdalisue** [comment]
Thanks @traeki to explain the current situation and @rforgione to understand ;-)

Yes I changed things a lot in https://github.com/lambdalisue/jupyter-vim-binding/pull/51 I really recommend you to try the new approach while this is really really useful.

You can find a new concept at https://github.com/lambdalisue/jupyter-vim-binding/wiki/Concept or hit `<F1>` in your jupyter notebook to find a new mappings ;-)

P.S.

@traeki 

> Some of the other modified bindings collided with OS X bindings I use daily, so I had to do that myself.

What kind of mappings? Editing `js` file directly is not really recommended. https://github.com/lambdalisue/jupyter-vim-binding#customization might help you to overwrite the default mappings.

**Comment by traeki** [comment]
Eh, the number of steps listed in that customization document feels daunting.  I wasn't into it.

I only needed to change a couple of things.  Specifically, you changed ctrl-1/2/3 to cmdtrl-1/2/3, and I have the cmdtrl-digits bound to OS X spaces, so that was a big problem.  I changed them back.

In the future, I'll just overwrite them again when I update.  Not a big deal.

**Comment by traeki** [comment]
One thing I'm struggling with:  I regularly want to duplicate the current cell into a new cell.  I can do this by Shift-Esc'ing out to Jupyter mode and hitting 'yyp'.  But although the help shortcuts list y,y and p as the way to do this from "command mode", those seem to copy and paste the current line (as expected) instead.

So two problems, here:  1) the "command-mode" shortcut is wrong or the "command-mode" section is mislabeled, or both.  2) I don't know how to copy paste a cell without going to Jupyter mode, and since the latter is sort of discouraged now I think there should be a way to manipulate cells from within command mode.  Suggestions?

**Comment by traeki** [comment]
Oh, wait, I get it now.  ^o,y,y , ^o,p does what I want.  So, this means that the "edit-mode" and "command-mode" are incorrectly labeled on the help menu, I think.  Or things are in the wrong bin, or something.  In particular, "Enter" does go from what is currently listed as "command-mode" (Jupyter-mode) into "edit-mode" (actual command-mode), but Esc does NOT go from "edit-mode" (command-mode) into "command-mode" (Jupyter-mode).

Confused?  ME TOO!  We should fix these help documents...

**Comment by lambdalisue** [comment]
true. well now i feel that i might change the terms to Command mode, Edit (Normal) mode, Edit (Insert) mode, or what ever. Any other ideas?

**Comment by lambdalisue** [comment]
@traeki Let's move onto #56 
@rforgione Please close the issue if you feel things are done :-)
