### ISSUE TITLE
ESC takes you to Jupyter's command mode in Safari.

### ISSUE THREAD

**Issue by ElDeveloper** [lambdalisue/jupyter-vim-binding#65]
### Summary

Hitting `<Esc>` takes me to Jupyter's command mode in Safari, Chrome however works just fine.
### Environment
- Operating system : (e.g. Mac OS X 10.11.3)
- Web browser : (e.g. Safari 9.0.3)
- Version or revision of Jupyter Notebook : (e.g. 4.1)
- Revision of jupyter-vim-binding : (e.g. 3e4030da4d23094840baa6967b99b965bea4144b)
### Behavior

Hitting `<Esc>` takes me to Jupyter's command mode in Safari, Chrome however works just fine.
#### Expected

It shouldn't take me to Jupyter's command mode.
#### Actual

It takes me to Jupyter's command mode.
### Step by step procedure
1. Start local Jupyter Notebook by `jupyter notebook`
2. Access http://localhost:xxxx/ in Safari
3. Enter insert mode in a cell, then hit `<Esc>`, you will be taken to Jupyter's command mode.
### What you have done to solve the issue

For example, the behavior is confirmed with Safari 9.0.3 and could not be reproduced in Firefox but Chrome.

**Comment by lambdalisue** [comment]
Thanks! ok, I'll check it prob next week. ping me if no further responce after next week :-)

**Comment by ElDeveloper** [comment]
Friendly _ping_.

**Comment by lambdalisue** [comment]
Thanks and sorry for late reply.

I tried with Safari Version 9.0.3 (11601.4.4) on OS X El Capitan (10.11.3) + jupyter-vim-binding  ad4e35e on Jupyter 4.2 and found:
- `<Esc>` does nothing in _Command mode_ but `<S-Esc>` (Expected behavior)
- **None of Vim mappings worked** in _Command mode_ (Unexpected behavior)

So it seems that the situation is a bit different from yours. In my case, none of Vim mappings worked even in [CodeMirror's Vim mode](https://codemirror.net/demo/vim.html) it self, mean that jupyter-vim-binding can not support Safari somehow.

Which exact version of Safari did you use? Not sure why CodeMirror's Vim mode itself does not work in my Safari...

**Comment by ElDeveloper** [comment]
@lambdalisue, thanks for looking into this. I'm using `Version 9.1 (11601.5.17.1)` in OS X El Capitan 10.11.4.

When I go to the example in the code mirror website, I can move around the text and even enter insert mode, but as soon as I hit `<Esc>` to exit insert mode, the text-box itself seems to no longer be in focus and I'm no longer able to execute any vim command. I think this points that the problem is CodeMirror itself not `jupyter-vim-binding`.

I also noticed this in there:

> The CodeMirror vim bindings do not have an active maintainer.

**Comment by lambdalisue** [comment]
> but as soon as I hit <Esc> to exit insert mode, the text-box itself seems to no longer be in focus and I'm no longer able to execute any vim command. I think this points that the problem is CodeMirror itself not jupyter-vim-binding.

I see. Then jupyter-vim-binding does not work in Safari.

**Comment by ElDeveloper** [comment]
Thanks for looking into this.

**Comment by ElDeveloper** [comment]
Just FYI, I finally figured it out, another plugin was interfering with bindings, I deactivated it and it was all good.
